{% set name = "wq.core" %}
{% set version = "1.2.0" %}
{% set sha256 = "20733e926c752037f77da641a2a12e530d4f9727f98894e96d6916fb75b073b3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - click <6
    - pyyaml

test:
  commands:
    - conda list wq.core
    
about:
  home: 'https://github.com/wq/wq.core'
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: The core wq command line interface (CLI).
  description:  wq.core provides the core wq command line application for use by wq.app 
                and other modules in the wq framework.  
  doc_url: https://wq.io/1.0/docs/wq
  dev_url: https://github.com/wq/wq.core

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
