travis:
  secure:
    BINSTAR_TOKEN: TvyYyXfxOXhVwABGo3NgQnVVgMwKKjUDJEoUuWV8jb/Y2s2AWaA0HwR0DK1M/2ctCMAWjUYciFoI+mdEQM+kpIa+6oTh5G2/GyvjK6mgw7V2WvLkgKv9eteXkpS1H/LFmKHA+nPHiaasc9sg9Zv67sLQk1meZ3SemkX55r0YGGOHLqes1SUBHj76ErZYl74fsvPU016INrqOcj5obOM5ZUbJxZjpNyUUQaO5XSqHlQ4OgS/FFPiKpW/7w0FHtlfZCMv6RS9r544I7+GgxyS8L/J/F9UXTu7T3gPXLVealxHT3boRNeuVS29QnS3rs3nQC4w5foVOUdKPy2mg+Ptn6qvXfZzsdESWmU9S8fnkNuv46fpFxV5Yy+8jmuuznC6QVq2C/4qR7Om+jK45wQchxDe+dBidoPBx8NVqERCbWxfPK0u77g8AuK57xKpCc8b1bfrByZKgFLpq6ko59BODx52cy2ba5LBtFRnijNgvCojniM61K1TSzRaRkiX5SR0EeycCsf4axdwtFxiOcCTpnEFHHY0p92m8LXMnpg0XM5bg+07sBGIfy9TIrevet7jreg2KX2BS1IIRh9eoIwsuntyDGzgIsYrQ/CIJ/hNgyzgYKoSFFFy1aWLlEKHbxuXCHwqSs+OzaKNNVOfbEjpPcT64pO/GbG5P6NEuda2apZc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
