travis:
  secure:
    BINSTAR_TOKEN: KroIo/52mHKURlSzOkVpsUVe3lnFg2zN8dVmdArH84DO+t1Hxv3mSHOXZi1RWfZA3vwn9wzTe4doXoVlyzK7XcgJso9YsUTVkfakGrR9ksebSP/TBbsYn5/rV6nktYIajy7RroMxBUiaYtcBdgOJpGEck4nGJ1XUbCeaaPB9b9m9V5Qpsl5tFtBTDh07jj/FAlDPjPADF2Q/wNi/JBLASPB6a74hvnqpnpzEZCxXSrPMx8/qqETdgIj1vfWhYCPgphulTqBVzhZ+U+2TgnmF33xsOZ7cohOe5wcvYrmswzKbZ/fq1v1R6HGHOz/YAgHLnQuTUzybK8jYqvkdbfAR/kPrqq7vi4IZAmPFVguZQ68fgsVwauQFwOumIKNSqO2aYvHjhXxL7+L15GO9JEA1/9RgtfAfC/4aA5PU6iHiz6rJ5rTKhpxfPW/4buSCPt94DQy+SzQfCgneWEL1ygOgiPvJRDjMiWyH8VpFnHgh77X0j8XT4ABCb43YJibiSvKT1l0LO7XV8KkVtDL3vPT8J2bbIMRxU4RBc5t1LK4bHVdrhCG12ljjPR05oQZ1JVjpY5iaDWfRPXZN3W889Bq871ssZa17UpGXo8OZodkLoZqvWsJZvfLrKNdJtueJJmbvsWxCH/OyZtoj2JZZDHiqu6MDogRX2P/Ayiy8FbG1Wck=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
